spring.application.name=tvmaze-middleware
spring.data.mongodb.uri=mongodb+srv://tvmaze_user:K1234@tvmaze-cluster.nsfys8o.mongodb.net/?appName=tvmaze-cluster
spring.mongodb.uri=mongodb+srv://tvmaze_user:K1234@tvmaze-cluster.nsfys8o.mongodb.net/tvmaze_db?retryWrites=true&w=majority